[package]
name = "ds_store"
version = "0.1.0"
authors = ["Davis Silverman <sinistersnare@gmail.com>"]
edition = "2018"

[lib]
name = "ds_store"
path = "src/lib.rs"

[[bin]]
name = "example"
path = "src/bin.rs"

[dependencies]
byteorder = { version = "1.2", default-features = false }
